original_repo: https://github.com/vlctechhub/event-template

volunteers_form: ""
mentors_form: ""
attendees_form: ""

keywords: "tecnología, evento, charla, vlctechhub, valencia, legal, software, licencias, responsabilidades, incompatibilidades, abogado"
title: "Legal para dummies - 22 de marzo 2019 - VLCTechHub"
description: "¿A que siempre quisiste que te explicaran en tu idiomas aspectos legales del desarrollo de software? Pues con esta excusa aprovecharemos para hacer un recorrido a lo largo de la vida de un software, atacando los problemas legales que van apareciendo y ofreciendo algunas soluciones creativas."
ogimage: ""

sass:
    sass_dir: assets/_sass
    style: compressed
