original_repo: https://github.com/vlctechhub/event-template

volunteers_form: ""
mentors_form: ""
attendees_form: ""

keywords: "tecnología, evento, charla, vlctechhub, valencia"
title: "VLCTechHub"
description: ""
ogimage: ""

sass:
    sass_dir: assets/_sass
    style: compressed
